name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release Version
        required: true
        type: string
      channel:
        description: Channel to promote
        required: true
        default: Unstable
        type: string
      slug:
        description: Replicated App Slug
        required: false
        type: string
      api-endpoint:
        description: Replicated API Endpoint
        required: false
        type: string
      api-token:
        description: Replicated API Token
        required: false
        type: string

env:
  CHART_NAME: app

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.0

      - name: Package Helm chart
        run: |
          helm package \
            --app-version=${{ inputs.version }} \
            --version=${{ inputs.version }} \
            ./charts/${{ env.CHART_NAME }}

      - name: Prepare release directory
        run: |
          mkdir -p ./build
          cp ./charts/${{ env.CHART_NAME }}-${{ inputs.version }}.tgz ./build/
          cp ./replicated/*.yaml ./build/

      - name: Prepare API parameters
        id: prepare-api
        run: |
          if [ -z "${{ inputs.slug }}" ]; then
            echo "replicated-app=${{ secrets.REPLICATED_APP }}" >> $GITHUB_OUTPUT
          else
            echo "replicated-app=${{ inputs.slug }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.api-endpoint }}" ]; then
            echo "api-endpoint=https://api.replicated.com/vendor" >> $GITHUB_OUTPUT
          else
            echo "api-endpoint=${{ inputs.api-endpoint }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.api-token }}" ]; then
            echo "api-token=${{ secrets.REPLICATED_API_TOKEN }}" >> $GITHUB_OUTPUT
          else
            echo "api-token=${{ inputs.api-token }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Replicated release
        uses: replicatedhq/action-kots-release@configurable-endpoint
        with:
          replicated-app: ${{ steps.prepare-api.outputs.replicated-app }}
          replicated-api-token: ${{ steps.prepare-api.outputs.api-token }}
          replicated-api-origin: ${{ steps.prepare-api.outputs.api-endpoint }}
          yaml-dir: ./build
          promote-channel: ${{ inputs.channel }}
          version: ${{ inputs.version }}
