name: Close Stale Issues

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 150
          days-before-stale: 7
          days-before-close: 3
          stale-issue-message: "This issue has been marked as stale because it has not had recent activity. Please update us if you still need assistance."
          close-issue-message: "This issue has been closed due to inactivity. If you are still experiencing this problem, please open a new issue and reference this one."
          stale-issue-label: "status::stale"
          close-issue-label: "status::closed"
          close-issue-reason: "not_planned"
          any-of-labels: "kind::support-request,kind::bug"
          debug-only: false
